title: Des Moines Real Estate Video Blog with Betsy Sarcone
description: Our mission is to be your best resource for Des Moines real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, your professional Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Betsy Sarcone
  title: Licensed REALTOR in IA
  license_number:
  about_markdown: |
    With a background in marketing, I started my real estate career in 2008. Growing up in the industry and in Des Moines, I had a fantastic foundation for building a real estate business.

    I have found success through focusing on the needs of my clients, always with honesty and a smile. Education is a huge part of my business, as I want to make sure you are making the best decision for your future--and for your wallet.

    Whether you are a first time homebuyer, relocating or looking to sell a home I have the knowledge you need to make the right decision. Call or email me today to find out how I have so many happy clients!
  brand:
  brokerage: Keller Williams Greater Des Moines
  market: Des Moines
  address: 4001 Westown Parkway West Des Moines, IA 50266
  phone: 515-329-0840
  phone_type:
  phone2:
  phone2_type:
  email: Sarconeteam@kw.com
  url: http://betsysarcone.com

forms:
  sitekey:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Home?"
    CTA_text2: "Search the entire MLS for your home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BetsyRealEstate
  linkedin_url: https://www.linkedin.com/pub/betsy-sarcone/4/42a/a80
  youtube_url: https://www.youtube.com/channel/UCGyxV-4WG1r8YwWhaKl46zg
  twitter_url: https://twitter.com/BetsySarcone
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/BSarcone/
  trulia_url: http://www.trulia.com/profile/betsy-sarcone-agent-west-des-moines-ia-4129910/overview
  yelp_url: http://www.yelp.com/biz/betsy-sarcone-keller-williams-realty-greater-des-moines-clive
  podcast_url: https://itunes.apple.com/us/podcast/greater-des-moines-real-estate/id1066408058?mt=2
  google_business_url:

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Des Moines Real Estate Video Blog
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
  header_overlay: rgba(0, 0, 0, 0.3)

site_colors:
  brand_color: '#00a1b0'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 5px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
